GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### Find SONGS REQUEST
GET http://localhost:3000/songs/2

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title":"Hello Music",
    "artists":["Sigla"],
    "releasedDate":"2024-11-12",
    "duration":"02:12",
    "lyrics":""
}


### Update SONGS REQUEST
PUT http://localhost:3000/songs/1

### Update SONGS REQUEST
DELETE http://localhost:3000/songs/1